"""empty message

Revision ID: 2a5fdb834d35
Revises: 1d337e183d47
Create Date: 2016-02-01 18:30:15.449000

"""

# revision identifiers, used by Alembic.
revision = '2a5fdb834d35'
down_revision = '1d337e183d47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
