"""empty message

Revision ID: 4b7b5a7ddc5c
Revises: 2a5fdb834d35
Create Date: 2016-02-01 18:31:56.369000

"""

# revision identifiers, used by Alembic.
revision = '4b7b5a7ddc5c'
down_revision = '2a5fdb834d35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('logo_path', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'logo_path')
    ### end Alembic commands ###
