"""empty message

Revision ID: d620dac63d6
Revises: 9ef49beab95
Create Date: 2016-02-07 15:07:22.938000

"""

# revision identifiers, used by Alembic.
revision = 'd620dac63d6'
down_revision = '9ef49beab95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
